server:
  port: 9002
  ssl:
    key-store:          "classpath:keystore.p12"
    key-store-password: "12345678"
    key-store-type:     "PKCS12"
    key-alias:          "tomcat"

spring:
  security:
    oauth2:
      client:
        registration:
          freee:
            provider:                     "freee"
            client-name:                  "Freee"
            
            client-id:                    "[env]"
            client-secret:                "[env]"
            redirect-uri:                 "{baseUrl}/login/oauth2/code/{registrationId}"
            
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "POST"
            
            scope:
              - account
        provider: 
          freee:
            authorization-uri:   "https://accounts.secure.freee.co.jp/public_api/authorize"
            token-uri:           "https://accounts.secure.freee.co.jp/public_api/token"
            user-info-uri:       "https://api.freee.co.jp/hr/api/v1/users/me"

logging:
  level:
    com.example: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG